version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  front:
    image: node:latest
    container_name: vue_frontend
    working_dir: /front
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
      - api

  api:
    image: python:3.11
    container_name: fastapi_backend
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - mongo
    env_file:
      - ./app/.env

volumes:
  mongo_data:
    driver: local